### ISSUE TITLE
Civilian casualty cap plugin fn_postinit only runs on the server (HC COMPTATABILITY)

### ISSUE THREAD

**Issue by xJenny99x** [Neefay/BromA-A3-Framework-Mark3#12]
waitUntil{mission_ai_controller};
if (!mission_ai_controller) exitWith {};

instead of 

(!isServer) exitWith {};

@ line2

**Comment by Neefay** [comment]
All of the functions are broadcast and made public by the server, and as such the Headless Client is able to assign them to the civilian units' Event Handlers.
