### ISSUE TITLE
fn_ACE_RevivePlayer

### ISSUE THREAD

**Issue by snekibreki** [Neefay/BromA-A3-Framework-Mark3#23]
Rsdn commeted a weird issue with the revivePlayer function from ACE, so I went ahead and checked out the function in question.

Turns out I'm a bit confused by what I'm seeing in here. Is the correct function to call  `BRM_ACE_fnc_AGM_RevivePlayer` or `BRM_ACE_fnc_ACE_RevivePlayer`?

**Comment by xJenny99x** [comment]
http://puu.sh/iSAH5/78033a7644.png
check the functions.cpp for ace3
in here you can see
class ACE_RevivePlayer {}; 

Therefor the correct usage would be
BRM_ACE_fnc_ACE_RevivePlayer

**Comment by snekibreki** [comment]
Corrected in commit `4df4a7becfc7868323f067a588bb002fee36e043`.
