### ISSUE TITLE
ADD ASR AI Function : fnc_showHideNVG

### ISSUE THREAD

**Issue by xJenny99x** [Neefay/BromA-A3-Framework-Mark3#26]

**Comment by xJenny99x** [comment]
http://88.196.231.158/2015-10-08_18-42-51t125.txt

**Comment by xJenny99x** [comment]
Running this once after the loadout has been given to a unit should suffice

**Comment by Neefay** [comment]
I'm not entirely sure where and what is this function for.

**Comment by Neefay** [comment]
Test comment.

**Comment by geroge-011** [comment]
Ahh, to loadout to remove ai NVG if daytime is not good time
