### ISSUE TITLE
What now?

### ISSUE THREAD

**Issue by BruceAlmightyy** [Neefay/BromA-A3-Framework-Mark3#29]
Where do you put it? Nothing here says how to use it.

**Comment by sargken** [comment]
Well you must know how to develop missions.

**Comment by BruceAlmightyy** [comment]
So.....not going to help?

**Comment by sargken** [comment]
The whole thing is the mission and its all modular.

**Comment by BruceAlmightyy** [comment]
so what directory do you put the file? Main Arma 3?

**Comment by sargken** [comment]
If you find the wiki on github it will help you. I read it earlier and explained some things i was wondering if u cant find it ill get you the link tomorrow.

**Comment by Neefay** [comment]
I've written a short guide on how to install and run everything - sorry about that!

https://github.com/Neefay/BromA-A3-Framework-Mark3/wiki#installing
