### ISSUE TITLE
check possible issues with scores

### ISSUE THREAD

**Issue by xJenny99x** [Neefay/BromA-A3-Framework-Mark3#30]
double scores for players, no scores for enemy ai ? may be mission specific issue

**Comment by Neefay** [comment]
ACE bug, "Killed" EH basically point only to the unit who died as both the killer and victim.

**Comment by QuiZNo** [comment]
>needing to confirm your kills with the scoreboard

**Comment by snekibreki** [comment]
punch it chewie
