### ISSUE TITLE
remove bodies on DC / cleanup dead bodies in spawn on mission start.

### ISSUE THREAD

**Issue by xJenny99x** [Neefay/BromA-A3-Framework-Mark3#33]
If somone's game crashes or he dc's before his loadout script has ran, the dead body will have vanilla gear, and people can pick up MXs and Katibas.

Also when people crash they will produce a body every time they do. Causing issues when people can pick up sniper rifles and extra AT. ( bad for missions where I want AT to be AT rifleman only )

**Comment by Neefay** [comment]
Fixed as a mod.
