### ISSUE TITLE
Question: DAC plugin to create zones mid mission (DAC_fNewZone)

### ISSUE THREAD

**Issue by Zriel88** [Neefay/BromA-A3-Framework-Mark3#37]
Hi!,
I'm using the framework to create a mission and would like to now if it is possible to create a new zone mid mission using the plugin syntax, just like when using the DAC function "DAC_fNewZone".
From tests, it doesn't seem possible.
Thanks in advance

**Comment by Neefay** [comment]
Sorry dude, that's a functionality I never got around to implementing into the plugin because the original function just gave me lots of headaches. That said, I think if you use the regular DAC function it should work normally. Hope that helps.
