### ISSUE TITLE
Time Limit Plugin different endings for coop,tvt

### ISSUE THREAD

**Issue by xJenny99x** [Neefay/BromA-A3-Framework-Mark3#9]
The time limit plugin currently is only set to call the defeat ending

LINE27:

["defeat"] call BRM_fnc_callEnding;

Should be :
	if (mission_game_mode == "COOP") then {
        ["defeat"] call BRM_fnc_callEnding;
        } else {
        ["side_a_defeat"] call BRM_fnc_callEnding;
        };

**Comment by Neefay** [comment]
Fixed.
